alias: Rolladen Sofa (NEU)
description: ""
trigger:
  - platform: template
    value_template: >-
      {{ states('sensor.helligkeitssensor_lux') | float <=
      states('input_number.rolladen_sichtschutz_start') | float and now() >=
      today_at('16:00') and sichtschutz }}
    id: Start Sichtschutz
    alias: Start Sichtschutz
  - platform: time
    at: "08:00:00"
    alias: Ende Sichtschutz (8 Uhr)
    id: Ende Sichtschutz
  - platform: template
    value_template: >-
      {{ states('sensor.helligkeitssensor_lux') | float <=
      states('input_number.rolladen_verdunklung_start') | float and now() >=
      today_at('16:30') and verdunklung }}
    id: Start Verdunklung
    alias: Start Verdunklung
  - platform: template
    value_template: >-
      {{ states('sensor.helligkeitssensor_lux') | float >=
      states('input_number.rolladen_verdunklung_ende') | float and now() <
      today_at('08:00') and not sichtschutz }}
    alias: Ende Verdunklung
    id: Ende Verdunklung
  - platform: template
    value_template: >-
      {{ states('sensor.helligkeitssensor_lux') | float <=
      states('input_number.rolladen_beschattung_ende') | float }}
    alias: Ende Beschattung
    id: Ende Beschattung
    for:
      hours: 0
      minutes: 15
      seconds: 0
  - platform: state
    entity_id:
      - binary_sensor.fenster_wohnzimmer_sofa
    to: "on"
    alias: Fenster offen
    from: "off"
    id: Fenster offen
  - platform: numeric_state
    entity_id: sensor.lumi_lumi_weather_temperature_2
    below: 0
    alias: Frost
    id: Start Frost
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Start Sichtschutz
        sequence:
          - if:
              - condition: state
                entity_id: binary_sensor.fenster_wohnzimmer_sofa
                state: "on"
            then:
              - wait_for_trigger:
                  - platform: state
                    entity_id:
                      - binary_sensor.fenster_wohnzimmer_sofa
                    to: "off"
          - device_id: 1b6707e31dc49e79622da1d0c17bace2
            domain: cover
            entity_id: ebdf12b2fafce5b20780973c7b60e546
            type: set_position
            position: 35
      - conditions:
          - condition: trigger
            id:
              - Ende Sichtschutz
        sequence:
          - if:
              - condition: time
                weekday:
                  - sat
                  - sun
            then:
              - delay:
                  hours: 0
                  minutes: 30
                  seconds: 0
                  milliseconds: 0
          - device_id: 1b6707e31dc49e79622da1d0c17bace2
            domain: cover
            entity_id: ebdf12b2fafce5b20780973c7b60e546
            type: open
      - conditions:
          - condition: trigger
            id:
              - Start Verdunklung
        sequence:
          - if:
              - condition: state
                entity_id: binary_sensor.fenster_wohnzimmer_sofa
                state: "on"
            then:
              - wait_for_trigger:
                  - platform: state
                    entity_id:
                      - binary_sensor.fenster_wohnzimmer_sofa
                    to: "off"
          - device_id: 1b6707e31dc49e79622da1d0c17bace2
            domain: cover
            entity_id: ebdf12b2fafce5b20780973c7b60e546
            type: set_position
            position: 30
      - conditions:
          - condition: trigger
            id:
              - Ende Verdunklung
        sequence:
          - device_id: 1b6707e31dc49e79622da1d0c17bace2
            domain: cover
            entity_id: ebdf12b2fafce5b20780973c7b60e546
            type: open
      - conditions:
          - condition: trigger
            id:
              - Ende Beschattung
        sequence:
          - device_id: 1b6707e31dc49e79622da1d0c17bace2
            domain: cover
            entity_id: ebdf12b2fafce5b20780973c7b60e546
            type: open
      - conditions:
          - condition: trigger
            id:
              - Fenster offen
        sequence:
          - if:
              - condition: device
                device_id: 1b6707e31dc49e79622da1d0c17bace2
                domain: cover
                entity_id: ebdf12b2fafce5b20780973c7b60e546
                type: is_position
                below: 80
            then:
              - service: scene.create
                data:
                  scene_id: before_cover_kue_links
                  snapshot_entities:
                    - cover.eg_az
              - device_id: 1b6707e31dc49e79622da1d0c17bace2
                domain: cover
                entity_id: ebdf12b2fafce5b20780973c7b60e546
                type: set_position
                position: 80
              - wait_for_trigger:
                  - platform: state
                    entity_id:
                      - binary_sensor.fenster_wohnzimmer_sofa
                    to: "off"
              - service: scene.turn_on
                data: {}
                target:
                  entity_id: scene.before_cover_kue_links
    enabled: true
mode: single
trigger_variables:
  sichtschutz: false
  verdunklung: false
